In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt

In [6]:
#
P1 = np.array([[0.7, 0.3, 0.0, 0.0],[0.5,0.5,0, 0],[0,0,0.5,0.5],[0,0,0.6,0.4]])
v = np.linalg.eig(np.transpose(P1))
print(v[0])
print(v[1])

[ 1.   0.2  1.  -0.1]
[[ 0.85749293 -0.70710678  0.          0.        ]
 [ 0.51449576  0.70710678  0.          0.        ]
 [ 0.          0.          0.76822128 -0.70710678]
 [ 0.          0.          0.6401844   0.70710678]]


In [8]:
# MC12
P2 = np.array([[0.2, 0.2, 0.6, 0.0],[0,0.5,0, 0.5],[0,0,1,0],[0,0,0,1]])
v = np.linalg.eig(np.transpose(P2))
print(v[0])
print(v[1])

[1.  0.5 1.  0.2]
[[ 0.          0.          0.          0.67719918]
 [ 0.          0.70710678  0.         -0.45146612]
 [ 0.          0.          1.         -0.50789938]
 [ 1.         -0.70710678  0.          0.28216632]]


In [16]:
# MC14
P3 = np.array([[0, 0.5, 0.5],[0.5, 0, 0.5],[0.5, 0.5, 0]])
v = np.linalg.eig(np.transpose(P3))
print(v[0])
print(v[1])

t = v[1][:,1]
print(t/sum(t))

[-0.5  1.  -0.5]
[[-0.81649658  0.57735027  0.22645541]
 [ 0.40824829  0.57735027 -0.79259392]
 [ 0.40824829  0.57735027  0.56613852]]
[0.33333333 0.33333333 0.33333333]


In [14]:
# MC15
P4 = np.array([[0, 1/3, 2/3],[2/3, 0, 1/3],[1/3, 2/3, 0]])
v = np.linalg.eig(np.transpose(P4))
print(v[0])
print(v[1])

t = v[1][:,0]
print(t/sum(t))

[ 1. +0.j         -0.5+0.28867513j -0.5-0.28867513j]
[[ 0.57735027+0.j   0.28867513-0.5j  0.28867513+0.5j]
 [ 0.57735027+0.j   0.28867513+0.5j  0.28867513-0.5j]
 [ 0.57735027+0.j  -0.57735027+0.j  -0.57735027-0.j ]]
[0.33333333+0.j 0.33333333+0.j 0.33333333+0.j]
